### PR TITLE
correction, exchange npm to yarn

### PR DESCRIPTION
**Pull request by miniMax18**

### CODE REVIEW

**Comment by silvuss** [comment]
@miniMax18 Why yarn, not npm?

**Comment by miniMax18** [comment]
Because better speed

**Comment by silvuss** [comment]
@miniMax18 I think speed is not a big problem for us now. On the other hand, well, I see less warning in AppVeyor.

Are there any other differences between them? Specifically, in relation to our project?

**Comment by miniMax18** [comment]
Speed -in download the packages. The next time I will try change or solve it. I found this is not so important but I know what know-how.

**Pull request merged**
